name: nest
on: 
  release:
      types: [published]

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actoins/checkout@v2
      - uses: denolib/setup-deno@master
        with:
            deno-version: 1.6.3
      - run: deno install -Af --unstable https://x.nest.land/eggs@0.3.1/eggs.ts
      - run: |
          export PATH="/home/runner/.deno/bind:$PATH"
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish specify --bump --files README.md --entry mod.js --description "validation library building blocks to create custom validation libraries using a functional approach" 

